trigger:
  branches:
    include:
     - main


pool: default

stages:
 - stage: StageInfraPipeline
   displayName: infra pipeline bana raha hu
   jobs:
    - job: terraforminstall
      displayName: infrainit job
      steps:
       - task: TerraformInstaller@1
         inputs:
           terraformVersion: 'latest'
       - task: TerraformTask@5
         inputs:
           provider: 'azurerm'
           command: 'init'
           backendServiceArm: 'azuresc'
           backendAzureRmResourceGroupName: 'my-rg'
           backendAzureRmStorageAccountName: 'mystorage456789032'
           backendAzureRmContainerName: 'mycontainer'
           backendAzureRmKey: 'ram.terraform.tfstate'
       - task: TerraformTask@5
         inputs:
           provider: 'azurerm'
           command: 'plan'
           environmentServiceNameAzureRM: 'azuresc'
       - task: TerraformTask@5
         inputs:
           provider: 'azurerm'
           command: 'apply'
           commandOptions: '-auto-approve'
           environmentServiceNameAzureRM: 'azuresc'