trigger:
  branches:
    include:
     - main


pool: default

stages:
 - stage: StageInitForInfraPipeline
   displayName: infra ki pipeline bana raha hu
   jobs:
    - job: JobInitForInfraPipeline
      displayName: infrainit job
      steps:
       